# Generated by Django 4.0.1 on 2022-05-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
