# Generated by Django 4.0.1 on 2022-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUser', '0002_alter_extendeduser_address_alter_extendeduser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(default=22),
        ),
    ]
