# Generated by Django 4.0.1 on 2022-05-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUser', '0003_extendeduser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='address',
            field=models.CharField(choices=[('Allahabad', 'Allahabad'), ('Patna', 'Patna'), ('Noida', 'Noida'), ('Ajamgadh', 'Ajamgadh'), ('Bhubneshwar', 'Bhubneshwar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
